### ISSUE TITLE
 All configured authentication methods failed

### ISSUE THREAD

**Issue by suab321321** [spmjs/node-scp2#138]
I m trying to send file using this line `client.scp(filePath, host, (err)=>{}`
host - "password:host.com:location" an (ec2 instance)

running this on windows 10 got this error
```
Error: All configured authentication methods failed
    at tryNextAuth (C:\Users\abhinavs\ORT_SOURCE\act\internalui\backend\node_modules\scp2\node_modules\ssh2\lib\client.js:294:17)
    at SSH2Stream.onUSERAUTH_FAILURE (C:\Users\abhinavs\ORT_SOURCE\act\internalui\backend\node_modules\scp2\node_modules\ssh2\lib\client.js:473:5)
    at SSH2Stream.emit (events.js:315:20)
    at parsePacket (C:\Users\abhinavs\ORT_SOURCE\act\internalui\backend\node_modules\scp2\node_modules\ssh2-streams\lib\ssh.js:3647:10)
    at SSH2Stream._transform (C:\Users\abhinavs\ORT_SOURCE\act\internalui\backend\node_modules\scp2\node_modules\ssh2-streams\lib\ssh.js:551:13)
    at SSH2Stream.Transform._read (_stream_transform.js:191:10)
    at SSH2Stream._read (C:\Users\abhinavs\ORT_SOURCE\act\internalui\backend\node_modules\scp2\node_modules\ssh2-streams\lib\ssh.js:212:15)
    at SSH2Stream.Transform._write (_stream_transform.js:179:12)
    at doWrite (_stream_writable.js:385:12)
    at writeOrBuffer (_stream_writable.js:367:5) {
  level: 'client-authentication'
}
```
it is showing that this is related to ssh2, but I cant understand how to fix it
OS - windows 10

**Comment by suab321321** [comment]
it got resolved closing it

**Comment by harshitsanghvi** [comment]
@suab321321 Could you please share how did this issue got resolved?
