### ISSUE TITLE
0.2.0 always gives "Error: handle is not a Buffer"

### ISSUE THREAD

**Issue by domenic** [spmjs/node-scp2#21]
See for example https://travis-ci.org/whatwg/streams/builds/43789094#L1383

compared to https://travis-ci.org/whatwg/streams/builds/39141547#L863 with 0.1.4

(<del>Also I might suck at shell scripting but I can't my Travis builds to fail when ssh2 throws an error :-/</del><ins>turns out I need to use Travis's `script` hook instead of `after_success`</ins>)

**Comment by AlexWell** [comment]
It does not work for me too.

**Comment by prisonier** [comment]
Exactly the same errors, does it come from scp2 or from a dependency ?

**Comment by ChristopherHackett** [comment]
Same here. if I drop the version down to ``0.1.4`` it works.

**Comment by airyland** [comment]
also with 0.2.2

**Comment by lepture** [comment]
Maybe it is related to https://github.com/spmjs/node-scp2/pull/32

**Comment by airyland** [comment]
@lepture 

https://github.com/spmjs/node-scp2/blob/master/lib/client.js#L225
https://github.com/spmjs/node-scp2/blob/master/lib/client.js#L234

The errors are "Permission denied".

![image](https://cloud.githubusercontent.com/assets/559179/7982068/5f789984-0ae6-11e5-9eac-0c8471c13069.png)

**Comment by Nepoxx** [comment]
Are you guys only seeing this on a specific platform?

For me (Ubuntu -> Ubuntu) scp2 0.2.2 creates the folders just fine, but for my coworker (Windows -> Ubuntu), the created folders lack the proper permissions (-x) and gives the `Error: handle is not a Buffer` error.

**Comment by Nepoxx** [comment]
The issue is that [`upload`](https://github.com/spmjs/node-scp2/blob/master/lib/client.js#L244) calls [`mkdir`](https://github.com/spmjs/node-scp2/blob/master/lib/client.js#L108) with incorrect attributes. `attrs.mode` is set to what `fs.stat()` returns for a file, which is not in the `CHMOD` format (0755 and whatnot).

Also, unfortunately, in windows the permissions on folders will not have the execute bit set, which means that folders will not be executable on the remote host.

```javascript
 attrs.mode = attrs.mode ? '0' + (attrs.mode & 0777).toString(8) : '0755'
```
 would solve the first issue, but I'm not sure how to deal with Windows permissions.

**Comment by dev4apart** [comment]
I am getting the following issue:

````
../wp-gulp-automation/node_modules/scp2/node_modules/ssh2/lib/SFTP/SFTPv3.js:227
    throw new Error('handle is not a Buffer');
          ^
Error: handle is not a Buffer
    at SFTP.write (../wp-gulp-automation/node_modules/scp2/node_modules/ssh2/lib/SFTP/SFTPv3.js:227:11)
    at ../wp-gulp-automation/node_modules/scp2/lib/client.js:208:18
    at FSReqWrap.wrapper [as oncomplete] (fs.js:527:17)

Process finished with exit code 1
`````

But I noticed that the file was created on the sftp-server but without content.

**Comment by xujihui1985** [comment]
any update? I have the same error in windows client

**Comment by xiaoyann** [comment]
because the dir of destination does not create before execute write

**Comment by vikramparth** [comment]
Any updates on this issue? I'm still running into it with the latest version of node-scp2.
