### ISSUE TITLE
ERROR: Argument must be a string

### ISSUE THREAD

**Issue by brendanjerwin** [spmjs/node-scp2#28]
Unable to get a copy from client to server working. Getting:
```
Message:
    Argument must be a string
Details:
    domain: [object Object]
    domainThrown: true
Stack:
TypeError: Argument must be a string
    at Connection._authNone (/home/brendanjerwin/projects/asset-server/services/asset-server/node_modules/scp2/node_modules/ssh2/lib/Connection.js:1336:24)
    at onSERVICE_ACCEPT (/home/brendanjerwin/projects/asset-server/services/asset-server/node_modules/scp2/node_modules/ssh2/lib/Connection.js:2412:12)
    at Parser.<anonymous> (/home/brendanjerwin/projects/asset-server/services/asset-server/node_modules/scp2/node_modules/ssh2/lib/Connection.js:133:5)
    at Parser.emit (events.js:95:17)
    at Parser.parsePacket (/home/brendanjerwin/projects/asset-server/services/asset-server/node_modules/scp2/node_modules/ssh2/lib/Parser.js:474:12)
    at Parser.execute (/home/brendanjerwin/projects/asset-server/services/asset-server/node_modules/scp2/node_modules/ssh2/lib/Parser.js:249:14)
    at Socket.<anonymous> (/home/brendanjerwin/projects/asset-server/services/asset-server/node_modules/scp2/node_modules/ssh2/lib/Connection.js:536:18)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
```

Calling it like this:

```
scpClient.scp(assetSourcePath, sshOptions, function (err) {
                if (err) {
                    trace('Error while scp: %s', err);
                } else {
                    trace('Copy completed.');
                }
           });
```

Where `sshOptions` looks something like this:

```
{ host: 'localhost', path: '/tmp/asset_build.QCvR' }
```

**Comment by brendanjerwin** [comment]
I found I needed to provide a username.
