### ISSUE TITLE
How to alter timeout?

### ISSUE THREAD

**Issue by adonespitogo** [spmjs/node-scp2#47]
```
[14:41:42] 'js:upload' errored after 10 s
[14:41:42] Error: Timed out while waiting for handshake
  at [object Object]._onTimeout (/home/adones/Projects/chaipcr/node_modules/scp2/node_modules/ssh2/lib/Connection.js:232:17)
  at Timer.listOnTimeout (timers.js:119:15)
```

**Comment by airbenich** [comment]
Is there a solution for this problem? And why does this happen? I have the same problem.

**Comment by airbenich** [comment]
Okay i found a solution: The appears because of the old ssh2 package that is included in this module. Update the included module via npm and the timeout is gone.

**Comment by joseluisq** [comment]
Does any news about that?

**Comment by airbenich** [comment]
include a newer ssh2 version in the packages.json, updated view nom and it will work

**Comment by joseluisq** [comment]
Fine thanks.
Does appears that scp2 is a little bit forgotten?
